"""add_talk_priority_rank

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-02 17:28:02.639334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, Sequence[str], None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talks', sa.Column('priority_rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_talks_priority_rank'), 'talks', ['priority_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_talks_priority_rank'), table_name='talks')
    op.drop_column('talks', 'priority_rank')
    # ### end Alembic commands ###
